repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.2.1"
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: mixed-line-ending
  # see https://github.com/biomejs/pre-commit/blob/main/.pre-commit-hooks.yaml
  - repo: local
    hooks:
      - id: biome-format
        name: biome format
        entry: ./nextjs/node_modules/.bin/biome format --config-path ./nextjs/biome.json --write --files-ignore-unknown=true --no-errors-on-unmatched
        language: system
        types: [text]
        files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css|svelte|vue|astro|graphql|gql)$"
      - id: biome-check
        name: biome check
        entry: ./nextjs/node_modules/.bin/biome check --config-path ./nextjs/biome.json --write --files-ignore-unknown=true --no-errors-on-unmatched
        language: system
        types: [text]
        files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css|svelte|vue|astro|graphql|gql)$"
