services:
  # postgres:
  #   image: postgres:17
  #   container_name: postgres
  #   environment:
  #     POSTGRES_DB: ifp
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   ports:
  #     - "5432:5432"

  scrapers:
    build:
      context: .
      dockerfile: docker/scrapers/Dockerfile
    container_name: scrapers
    #    depends_on:
    #      - postgres
    volumes:
      - ./scrapers:/app/scrapers
    environment:
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_REGION=${S3_REGION}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    command: sleep infinity

  dbt:
    build:
      context: .
      dockerfile: docker/dbt/Dockerfile
    container_name: dbt
#    depends_on:
#      - postgres
    volumes:
      - ./dbt_ifp:/dbt_ifp
    env_file:
      - .env
    command: sleep infinity

  # nocodb:
  #   image: nocodb/nocodb:latest
  #   container_name: nocodb
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     NC_DB: "pg://postgres:5432?u=app_user&p=app_password&d=app_db"  # todo : user & passwd
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - nocodb_data:/usr/app/data

  nextjs:
    build:
      context: .
      dockerfile: docker/nextjs/Dockerfile
    container_name: nextjs
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/app
      - /app/node_modules
      - /app/.next
    # env_file:
    #   - .env
    command: npm run dev

volumes:
  postgres_data:
  nocodb_data:

