name: Pipeline Import & Generate


on:
  workflow_dispatch:
    inputs:
      annee:
        description: "Année à traiter"
        required: true
        default: "2026"

jobs:
  import_generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ifp_sources image
        run: docker build -t local/ifp_sources -f docker/ifp_sources/Dockerfile .

      - name: Run Import & Generate
        run: |
          docker run \
            -v "${GITHUB_WORKSPACE}/data:/github/workspace/data" \
            -e POSTGRES_HOST="${{ secrets.POSTGRES_HOST }}" \
            -e POSTGRES_USER="${{ secrets.POSTGRES_USER }}" \
            -e POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
            -e POSTGRES_DB="${{ secrets.POSTGRES_DB }}" \
            local/ifp_sources \
            python ifp_sources/import_and_generate.py --pipeline import --annee "${{ github.event.inputs.annee }}"
