name: Tests sur les scrapers

on:
  pull_request:
    paths:
      - 'scrapers/**'
  push:
    branches: [main]
    paths:
      - 'scrapers/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Construire l'image Docker
        run: docker compose build scrapers

      # Run pytest tests, except those requiring a navigator, marked with a "live" tag
      - name: Lancer les tests
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_REGION: ${{ vars.S3_REGION }}
          S3_ENDPOINT_URL: ${{ vars.S3_ENDPOINT_URL }}
          S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
        run: |
          docker compose run --rm -w /app/scrapers -e PYTHONPATH=/app/scrapers scrapers \
          uv run pytest -m "not live" -v