name: Lancer les Scrapers (Manuel)

on:
  # Permet de lancer ce workflow manuellement depuis l'onglet "Actions" de GitHub
  workflow_dispatch:

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v6

      - name: Construire l'image Docker
        # On construit l'image Docker en utilisant la configuration de docker-compose.yml
        run: docker compose build scrapers

      - name: Lancer les scrapers
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_REGION: ${{ vars.S3_REGION }}
          S3_ENDPOINT_URL: ${{ vars.S3_ENDPOINT_URL }}
          S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
        run: |
          docker compose run --rm scrapers -w /app/scrapers python -m main

      - name: Sauvegarder les fichiers dans les Artefacts
        uses: actions/upload-artifact@v6
        with:
          name: resultats-scrapers
          # Chemin vers le dossier de sauvegarde des fichiers de scraping
          path: scrapers/data
          # Optionnel : durée de conservation pour ne pas saturer votre espace GitHub
          retention-days: 14
